// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordToPdfExporter.Infrastructure.Data;

#nullable disable

namespace WordToPdfExporter.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WordToPdfExporterContext))]
    [Migration("20241219160840_RemoveCurrentDocument")]
    partial class RemoveCurrentDocument
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("WordToPdfExporter.Core.Exporting.DocumentExport", b =>
                {
                    b.Property<int>("DocumentExportRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentExportRequestId");

                    b.ToTable("DocumentExports");
                });
#pragma warning restore 612, 618
        }
    }
}
